### ISSUE TITLE
Unkown error when launcher does not have a control panel connected

### ISSUE THREAD

**Issue by capralden** [ArjanSeijs/OC_ICBM_Addon#6]
An error while trying to interact with Launcher platform, while set or get target position in console i see "Unknown error". Also method "containsMissile()" always return false. (OpenComputers-MC1.12.2-1.7.5.192, ICBM-classic-1.12.2-4.0.1b75, OpenComputersICBMAddon-1.2)

Here is code i used:
[ICBM_demo.txt](https://github.com/ArjanSeijs/OC_ICBM_Addon/files/5487079/ICBM_demo.txt)

And some screens:
![2020-11-04_13 09 31](https://user-images.githubusercontent.com/46059433/98098611-9e55f980-1e9f-11eb-80ca-042baaa5292a.png)
![2020-11-04_13 10 04](https://user-images.githubusercontent.com/46059433/98098612-9f872680-1e9f-11eb-97f3-0e984ce6e3ff.png)

**Comment by ArjanSeijs** [comment]
You need to add a launcher control panel for it to work.

I'll see if I can update the error message to reflect that.

**Comment by capralden** [comment]
Thanks, it works!)
